language: c++
# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos, netCDF.
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo apt-get update -qq
  # A number of dependencies here should be covered by libtrilinos-dev.
  - sudo apt-get install cmake gfortran libboost-dev libhdf5-openmpi-7 libeigen3-dev libtbb-dev libboost-system-dev libptscotch-dev libmumps-dev libparmetis-dev liblapack-dev libnetcdfc libtrilinos libtrilinos-dev
install:
  - cmake -DBUILD_SHARED_LIBS:BOOL=TRUE -DCMAKE_CXX_COMPILER:STRING=mpicxx -DCMAKE_Fortran_COMPILER:STRING=mpif90 .
  - make
# command to run tests
script: ctest
