language: c++
# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos.
  #- sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo apt-get update -qq
  # A number of dependencies here should be covered by libtrilinos-dev.
  # The following dependencies can all go once the Trilinos export system is
  # fixed.
  - sudo apt-get install libopenmpi-dev openmpi-bin
  #- sudo apt-get install libhdf5-openmpi-7 libhdf5-openmpi-dev
  #- sudo apt-get install libnetcdf libnetcdf-dev
  #- sudo apt-get install libboost-system-dev
  #- sudo apt-get install libmumps-dev libptscotch-dev binutils-dev
  - sudo apt-get install libptscotch-5.1 # should be added by Trilinos
  - sudo apt-get install libboost-dev libtbb-dev # should be added by Trilinos
  - sudo apt-get install cmake-data cmake
  - sudo apt-get install libgtest-dev libtribits-dev # shouldn't be necessary
  - sudo apt-get install trilinos-dev
install:
  - cmake -DBUILD_SHARED_LIBS:BOOL=TRUE -DCMAKE_CXX_COMPILER:STRING=mpicxx .
  - make
# command to run tests
script:
  - ctest -VV
