language: c++
# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos.
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo apt-get update -qq
  - sudo apt-get install libopenmpi-dev openmpi-bin
  # The -dev versions are definitely not needed since Trilinos doesn't expose
  # any of the interface of libptscotch. This can be fixed by the PRIVATE
  # keyword in the appropriate target_link_libraries() in Trilinos.
  - sudo apt-get install libptscotch-dev libmumps-dev libboost-program-options-dev
  - sudo apt-get install libboost-system-dev liblapack-dev binutils-dev
  - sudo apt-get install libhdf5-openmpi-7 libhdf5-openmpi-dev
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get install libboost-dev libtbb-dev # should be added by Trilinos
  - sudo apt-get install cmake-data cmake
  - sudo apt-get install libtribits-dev # shouldn't be necessary
  - sudo apt-get install trilinos-dev
  - sudo pip install cpp-coveralls
install:
  - cmake -DBUILD_SHARED_LIBS:BOOL=ON -DENABLE_GCOV:BOOL=ON -DCMAKE_CXX_COMPILER:STRING=mpicxx .
  - make VERBOSE=1
# command to run tests
script:
  - ctest -VV
# Submit to coveralls for coverage statistics
after_success:
  - coveralls --gcov-options '\-lp'
