language: c++
# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos, netCDF.
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo apt-get update -qq
  # A number of dependencies here should be covered by libtrilinos-dev.
  - sudo apt-get install gfortran libboost-dev libnetcdfc libtrilinos
install:
  - cmake -DCMAKE_CXX_COMPILER:STRING=mpicxx -DCMAKE_Fortran_COMPILER:STRING=mpif90 .
  - make
# command to run tests
script: ctest
