sudo: required
dist: trusty

language: python

python:
    - "3.4"

# compiler:
#   - gcc
#   # TODO static analyisis <http://clang-analyzer.llvm.org/scan-build.html>
#   # scan-build cmake && make
#   # problem: mpi.h

virtualenv:
  system_site_packages: true

# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos.
  - sudo add-apt-repository -y ppa:nschloe/eigen-nightly
  - sudo add-apt-repository -y ppa:nschloe/hdf5-backports
  - sudo add-apt-repository -y ppa:nschloe/mikado-nightly
  - sudo add-apt-repository -y ppa:nschloe/moab-nightly
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo add-apt-repository -y ppa:nschloe/sympy-backports2
  - sudo apt update -qq
  - sudo apt install -y libmoab-dev moab-bin
  - sudo apt install -y libopenmpi-dev openmpi-bin
  - sudo apt install -y trilinos-all-dev
  - sudo apt install -y libmikado-dev
  - sudo apt install -y libeigen3-dev
  - sudo apt install -y python3-sympy
  - sudo apt install -y astyle
  - sudo apt install -y catch
  # Should be added by trilinos/moab:
  - sudo apt install -y libmetis-dev libhdf5-mpi-dev
  # - sudo apt install -y cppcheck
  # - cppcheck --enable=all
  - export PATH="/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.5.1.linux.amd64/bin:/home/travis/.local/bin:/usr/local/rvm/gems/ruby-2.2.3/bin:/usr/local/rvm/gems/ruby-2.2.3@global/bin:/usr/local/rvm/rubies/ruby-2.2.3/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v4.1.2/bin:./node_modules/.bin:/usr/local/maven-3.1.1/bin:/usr/local/gradle/bin:/usr/local/clang-3.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/usr/local/rvm/bin"
  - sudo -H pip install meshio

install:
  - cmake -DBUILD_SHARED_LIBS:BOOL=ON -DENABLE_GCOV:BOOL=ON -DCMAKE_CXX_COMPILER:STRING=mpicxx -DCMAKE_SHARED_LINKER_FLAGS="$CMAKE_SHARED_LINKER_FLAGS -Wl,--no-undefined" .
  - make

# command to run tests
script:
  - ctest -VV

after_success:
  - bash <(curl -s https://codecov.io/bash)
